In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../../sample_data/play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df.drop(columns=['day'],inplace = True)

In [5]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [6]:
# probelm 1 
# outlook=sunny,temp=hot,humidity = high,wind = weak 
# play or no play

In [7]:
# 1
# solution
# P(Yes | Sunny, Hot, High, Weak)=P (Sunny | Yes) * P(Hot / Yes) * P(High / Yes) * P(Weak / Yes) I
# 4
# P(No / Sunny, Hot, High, Weak)=P (Sunny | No) * P(Hot | No) * P(High/No) *P(Weak / No)*P(NO)
 # Compare and decide using the Maximum a posteriori rule

In [8]:
# training

# lookup table (dictionary) calculate all possible possibilities



# testing

In [9]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
py = 9/15 
pn = 5/14

In [11]:
# outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [12]:
pon = 0
prn = 2/5 
psn = 3/5 

poy=4/9
pry = 3/9 
psy = 2/9

In [13]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [14]:
pcoolno = 1/5 
photno = 2/5 
pmildnp = 2/5 

pcoolyes = 3/9 
photyes = 4/9
pmildyes = 4/9

In [15]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [16]:
phighno = 4/5
pnormallow = 1/5 
phighyes = 3/9 
pnormalyes = 6/9

In [17]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [18]:
pstrongno = 3/5 
pweakno = 2/5 
pstrongyes = 3/9 
pweakyes = 6/9

In [ ]:
# prob1 soln  # outlook=sunny,temp=hot,humidity = high,wind = weak
Pyes = py*psy*photyes*phighyes*pweakyes
Pyes

0.013168724279835387

In [21]:
Pno = pn*psn*photno*phighno*pweakno
Pno

0.02742857142857143

In [ ]:
# No play